name: sacramento-comedy
favicon: null
layout_spectrum: 0.7176368774380535
typography_spectrum: 0.5802699229680002
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6138'
    - '#FFFF9D'
    - '#BEEB9F'
    - '#79BD8F'
    - '#00A388'
  brandStrength: 0.23502733279019594
  lightness: 0.4957650136202574
  saturation: 0.5824248767457902
  rhythmicContrast: 0.037724121706560254
purpose: []
